# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 19:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portal.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('ACS', 'Admin and Conference Services'), ('RE', 'Residential Engagement'), ('FO', 'Facilities Operations'), ('RSA', 'Resident Student Association'), ('NRHH', 'National Residence Hall Honorary')], max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, help_text="Use a 4-digit extension or full phone number. It'll be formatted automatically.", max_length=15)),
                ('building', models.CharField(blank=True, choices=[('', ''), ('Acacia', 'Acacia'), ('Birch', 'Birch'), ('Cypress', 'Cypress'), ('Fig', 'Fig'), ('Elm', 'Elm'), ('Holly', 'Holly'), ('Juniper', 'Juniper'), ('Manzanita', 'Manzanita'), ('Oak', 'Oak'), ('Pine', 'Pine'), ('Sycamore', 'Sycamore'), ('Valencia', 'Valencia'), ('Willow', 'Willow')], help_text='For live-on staff only.', max_length=10)),
                ('room', models.CharField(blank=True, max_length=3)),
                ('birthday', models.DateField(blank=True, help_text="The database requires you enter a year, but don't worry - it isn't shown in the directory :)", null=True)),
                ('photo', models.ImageField(blank=True, upload_to=portal.models.user_directory_path)),
                ('bio', models.TextField(blank=True)),
                ('pronouns', models.CharField(blank=True, choices=[('M', 'He/Him/His'), ('F', 'She/Her/Hers'), ('T', 'They/Them/Theirs'), ('', '')], max_length=10)),
                ('last_password_change', models.DateField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formID', models.SmallIntegerField(blank=True)),
                ('formName', models.CharField(default='', max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('qty', models.SmallIntegerField(default=0)),
                ('last_saved', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.Employee')),
            ],
            options={
                'verbose_name_plural': 'Form Data Records',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('context', models.CharField(choices=[('default', 'default'), ('primary', 'primary'), ('info', 'info'), ('success', 'success'), ('warning', 'warning'), ('danger', 'danger'), ('rose', 'rose')], default='info', max_length=10)),
                ('unread', models.BooleanField(default=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('customurl', models.CharField(help_text='Use a single word or multiple words separated by a dash(-)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Link')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('admin_only', models.BooleanField(default=False, help_text='If yes, this page will only be visible to Portal Administrators', verbose_name='Manager-Visible Only')),
                ('icon', models.CharField(default='do_not_disturb', help_text='For icon options, visit <a href="https://material.io/icons/" target="_blank">https://material.io/icons/</a>. If the icon name has a space, replae it with an underscore (_).', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Use this editor to customize what your homepage post will look like. Please note that the exact appearance may differ slightly.')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('header_color', models.CharField(choices=[('purple', 'purple'), ('blue', 'blue'), ('green', 'green'), ('orange', 'orange'), ('red', 'red'), ('rose', 'rose')], default='blue', max_length=7)),
                ('admin_only', models.BooleanField(default=False, help_text='If yes, this post will only be visible to Portal Administrators', verbose_name='Manager-Visible Only')),
                ('last_published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TabbedPageContent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Page')),
                ('parent', models.CharField(blank=True, choices=[('P', 'Programming'), ('M', 'Marketing'), ('C', 'Calendars'), ('F', 'Full-Time Staff Resources')], max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tab Content',
            },
            bases=('portal.page',),
        ),
    ]
