# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='If yes, this page will only be visible to Portal Administrators', verbose_name='Admin-Visible Only'),
        ),
        migrations.AlterField(
            model_name='post',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='If yes, this post will only be visible to Portal Administrators', verbose_name='Admin-Visible Only'),
        ),
    ]
