# Generated by Django 2.0.7 on 2018-12-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0003_auto_20181225_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_tag', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=60, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioPortType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayPortType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Asset')),
                ('type', models.CharField(max_length=20)),
            ],
            bases=('inventory.asset',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Asset')),
                ('USB_ports', models.PositiveIntegerField(default=2)),
                ('primary_domain', models.CharField(blank=True, choices=[('AD', 'AD'), ('ACAD', 'ACAD')], default='AD', max_length=4, null=True)),
                ('name', models.SlugField(blank=True, null=True, unique=True)),
                ('IP_address', models.CharField(blank=True, max_length=15, null=True)),
                ('audio_outputs', models.ManyToManyField(to='inventory.AudioPortType')),
                ('display_outputs', models.ManyToManyField(to='inventory.DisplayPortType')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.OperatingSystem')),
            ],
            bases=('inventory.asset',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Asset')),
                ('has_builtin_speakers', models.BooleanField(default=False)),
                ('USB_ports', models.PositiveSmallIntegerField(default=0)),
                ('audio_inputs', models.ManyToManyField(to='inventory.AudioPortType')),
                ('display_inputs', models.ManyToManyField(to='inventory.DisplayPortType')),
            ],
            bases=('inventory.asset',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'assigned_user': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Employee')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Asset'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Employee'),
        ),
        migrations.AddField(
            model_name='note',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Ticket'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Employee', verbose_name='Assigned to User'),
        ),
    ]
