# Generated by Django 2.0.7 on 2018-12-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayporttype',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
