# Generated by Django 2.0.7 on 2018-12-26 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181225_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Computer')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Monitor')),
                ('using', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.DisplayPortType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accesories'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='Asset_tag',
            new_name='asset_tag',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Asset'),
        ),
        migrations.AddField(
            model_name='computer',
            name='connected_monitors',
            field=models.ManyToManyField(through='inventory.MonitorConnection', to='inventory.Monitor'),
        ),
    ]
