# Generated by Django 2.0.7 on 2018-12-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181225_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='audio_inputs',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.AudioPortType'),
        ),
    ]
