# Generated by Django 2.0.7 on 2018-12-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20181225_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitorconnection',
            name='monitor',
            field=models.ForeignKey(error_messages={'unique': 'That monitor is already in use.'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.Monitor', unique=True),
        ),
    ]
