# Generated by Django 2.0.12 on 2019-06-07 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181225_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('C', 'Computer'), ('M', 'Monitor'), ('D', 'Mobile Device'), ('A', 'Accessory')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Asset')),
                ('name', models.SlugField(blank=True, null=True, unique=True)),
                ('model', models.ForeignKey(limit_choices_to={'type': 'D'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.AssetModel')),
            ],
            bases=('inventory.asset',),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.AddField(
            model_name='accessory',
            name='model',
            field=models.ForeignKey(limit_choices_to={'type': 'A'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.AssetModel'),
        ),
        migrations.AddField(
            model_name='computer',
            name='model',
            field=models.ForeignKey(limit_choices_to={'type': 'C'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.AssetModel'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='model',
            field=models.ForeignKey(limit_choices_to={'type': 'M'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.AssetModel'),
        ),
    ]
